/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlvanphongpham;

import Models.DBAccess;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ConfirmPass extends javax.swing.JFrame {

    /**
     * Creates new form ConfirmPass
     */
    private static String nameChange = "";
    private static String username = "";
    private static JTable tableql;
    private static JTable tablenv;

    public ConfirmPass(String username, String nameChange, JTable tableql, JTable tablenv) {
        initComponents();
        this.username = username;
        this.nameChange = nameChange;
        this.tableql = tableql;
        this.tablenv = tablenv;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nhập password");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jButton1)
                        .addGap(28, 28, 28)
                        .addComponent(jButton2)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String password = txtpassword.getText();
        try {
            DBAccess db = new DBAccess();
            String q = "Select * from NHAN_VIEN where TENDANGNHAP = '" + username + "' and MATKHAU = '" + password + "'";
            ResultSet rs = db.ExQuery(q);
            if (rs.next()) {
                String qur = "Select * from NHAN_VIEN where TENDANGNHAP='" + nameChange + "' and LAQUANLY = 1";
                ResultSet res = db.ExQuery(qur);
                if (res.next()) {
                    String qr = "Update NHAN_VIEN set LAQUANLY = 0 WHERE TENDANGNHAP = '" + nameChange + "'";
                    int ok = db.UpdateTable(qr);
                    if (ok == 1) {
                        bindTableQL();
                        bindTableNV();
                        JOptionPane.showMessageDialog(this, "Phân quyền thành công");
                        this.dispose();
                    }else {
                        JOptionPane.showMessageDialog(this, "Có lỗi xảy ra trong quá trình phân quyền");
                    }
                }else {
                    String qr = "Update NHAN_VIEN set LAQUANLY = 1 WHERE TENDANGNHAP = '" + nameChange + "'";
                    int ok = db.UpdateTable(qr);
                    if (ok == 1) {
                        bindTableQL();
                        bindTableNV();
                        JOptionPane.showMessageDialog(this, "Phân quyền hoàn tất");
                        this.dispose();
                    }else {
                        JOptionPane.showMessageDialog(this, "Có lỗi xảy ra trong quá trình phân quyền");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Sai tên tài khoản hoặc mật khẩu");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public void bindTableQL() throws ClassNotFoundException, SQLException {
        DBAccess db = new DBAccess();
        String q = "select TENDANGNHAP,TENHANVIEN, SDT, GIOITINH, NGAYSINH from NHAN_VIEN where LAQUANLY = 1";
        ResultSet res = db.ExQuery(q);
        DefaultTableModel model = (DefaultTableModel) tableql.getModel();
        model.setRowCount(0);
        while (res.next()) {
            String temp = "";
            String username = res.getString(1);
            String name = res.getString(2);
            String SDT = res.getString(3);
            String GIOITINH = res.getString(4);
            String NGAYSINH = res.getString(5);
            String[] row = {temp, username, name, SDT, GIOITINH, NGAYSINH};
            model.addRow(row);
        }
    }

    public void bindTableNV() throws ClassNotFoundException, SQLException {
        DBAccess db = new DBAccess();
        String q = "select TENDANGNHAP,TENHANVIEN, SDT, GIOITINH, NGAYSINH from NHAN_VIEN where LAQUANLY = 0";
        ResultSet res = db.ExQuery(q);
        DefaultTableModel model = (DefaultTableModel) tablenv.getModel();
        model.setRowCount(0);
        while (res.next()) {
            String temp = "";
            String username = res.getString(1);
            String name = res.getString(2);
            String SDT = res.getString(3);
            String GIOITINH = res.getString(4);
            String NGAYSINH = res.getString(5);
            String[] row = {temp, username, name, SDT, GIOITINH, NGAYSINH};
            model.addRow(row);
        }
        //tablenv.getColumnModel().getColumn(0).setCellRenderer(new NVRender());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmPass(username, nameChange, tableql, tablenv).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables
}
