/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlvanphongpham;

import Models.DBAccess;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author Admin
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    private static LoginForm form;
    private static String username = "";
    private static int action = 0;

    public MainForm(LoginForm form, String username) throws ClassNotFoundException, SQLException {
        initComponents();
        this.form = form;
        this.username = username;
        usernameds.setText("Hello " + username);
        tableql.getColumnModel().getColumn(0).setCellRenderer(new ThayDoiRender());
        tablenv.getColumnModel().getColumn(0).setCellRenderer(new NVRender());
        tablebanhang.getColumnModel().getColumn(0).setCellRenderer(new CheckBoxRender());
        displayPanel.setSelectedIndex(2);
        DBAccess db = new DBAccess();
        String q = "Select * from NHAN_VIEN where TENDANGNHAP = '" + username + "' and LAQUANLY = 1";
        ResultSet ok = db.ExQuery(q);
        if (!ok.next()) {
            btnphanquyen.hide();
        }
        addToComboBoxMatHang();
    }

    public void addToComboBoxMatHang() throws ClassNotFoundException, SQLException {
        DBAccess db = new DBAccess();
        String q = "Select DISTINCT TENLOAI from LOAI_MAT_HANG";
        ResultSet ok = db.ExQuery(q);
        while (ok.next()) {
            cbloaihang.addItem(ok.getString("TENLOAI"));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usernameds = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnphanquyen = new javax.swing.JButton();
        displayPanel = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablebanhang = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnluu = new javax.swing.JButton();
        btnboqua = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        checkDis = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtmota = new javax.swing.JTextArea();
        txtmathang = new javax.swing.JTextField();
        txtmamh = new javax.swing.JTextField();
        cbdvt = new javax.swing.JComboBox<>();
        cbloaihang = new javax.swing.JComboBox<>();
        txtgiaban = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableql = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablenv = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        usernameds.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        usernameds.setText("username ");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-user-100.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usernameds, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173)
                .addComponent(jLabel3)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(usernameds))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 976, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/box64.gif"))); // NOI18N
        jButton1.setText("Quản Lý Bán Hàng");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit.gif"))); // NOI18N
        jButton2.setText("Đăng xuất");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnphanquyen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user.gif"))); // NOI18N
        btnphanquyen.setText("Phân Quyền");
        btnphanquyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnphanquyenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnphanquyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnphanquyen, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 200, 660));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        tablebanhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Disable", "Nhóm mặt hàng", "Mã mặt hàng", "Mặt hàng", "Giá bán", "DVT", "Mô tả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablebanhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablebanhangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablebanhang);

        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Sửa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Thêm");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnluu.setText("Lưu");
        btnluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluuActionPerformed(evt);
            }
        });

        btnboqua.setText("Bỏ Qua");
        btnboqua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnboquaActionPerformed(evt);
            }
        });

        jLabel6.setText("Thông tin mặt hàng");

        jLabel7.setText("Loại MH");

        jLabel8.setText("Mã MH");

        jLabel9.setText("Giá bán");

        jLabel10.setText("Mặt hàng");

        jLabel11.setText("DVT");

        checkDis.setBackground(new java.awt.Color(255, 255, 255));
        checkDis.setText("Disable");

        jLabel12.setText("Mô tả");

        txtmota.setColumns(20);
        txtmota.setRows(5);
        jScrollPane4.setViewportView(txtmota);

        cbdvt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CÁI", "CHIẾC", "CÂY", "TỜ" }));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-add-20.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel8))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)))
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbloaihang, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgiaban, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmamh, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(checkDis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbdvt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 693, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtmathang, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(7, 7, 7)))
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(btnluu, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(btnboqua, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(btnluu)
                    .addComponent(btnboqua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel10)
                                .addComponent(jLabel12)
                                .addComponent(txtmathang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbloaihang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(txtmamh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbdvt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(checkDis)
                            .addComponent(txtgiaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(434, Short.MAX_VALUE))
        );

        displayPanel.addTab("tab2", jPanel4);

        jPanel3.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel1.setText("Nhân viên quản lý ");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Nhân viên bán hàng");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableql.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Thay đổi", "Tên Đăng Nhập", "Tên Nhân Viên", "SĐT", "Giới Tính", "Ngày Sinh"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableql.getTableHeader().setReorderingAllowed(false);
        tableql.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableqlMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableql);

        tablenv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Thay đổi", "Tên đăng nhập", "Tên nhân viên", "SĐT", "Giới Tính", "Ngày Sinh"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablenv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablenvMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablenv);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1399, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        displayPanel.addTab("tab1", jPanel3);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(653, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel5)
                .addContainerGap(506, Short.MAX_VALUE))
        );

        displayPanel.addTab("tab3", jPanel5);

        getContentPane().add(displayPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 70, 770, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnphanquyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnphanquyenActionPerformed
        displayPanel.setSelectedIndex(1);
        try {
            bindTableQL();
            bindTableNV();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnphanquyenActionPerformed
    public void bindSP() throws ClassNotFoundException, SQLException {
        DBAccess db = new DBAccess();
        String q = "select TENLOAI, MAMH, TENMH, GIABAN, DVT, MOTA from MAT_HANG, LOAI_MAT_HANG where LOAI_MAT_HANG.MALOAI = MAT_HANG.MALOAI and MAT_HANG.VOHIEUHOA = 0";
        ResultSet res = db.ExQuery(q);
        DefaultTableModel df = (DefaultTableModel) tablebanhang.getModel();
        df.setRowCount(0);
        while (res.next()) {
            String temp = "";
            String tenloai = res.getString(1);
            String mamh = res.getString(2);
            String tenmh = res.getString(3);
            String giaban = res.getString(4);
            String DVT = res.getString(5);
            String mota = res.getString(6);
            String[] obj = {temp, tenloai, mamh, tenmh, giaban, DVT, mota};
            df.addRow(obj);
        }
    }
    private void tableqlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableqlMouseClicked
        int selectRow = tableql.getSelectedRow();
        System.out.println(selectRow);
        TableModel model = tableql.getModel();
        if (selectRow != -1) {
            int ask = JOptionPane.showConfirmDialog(this, "Bạn có muốn thay đổi chức vụ của: " + model.getValueAt(selectRow, 2));
            if (ask != -1) {
                ConfirmPass p = new ConfirmPass(username, (String) model.getValueAt(selectRow, 1), tableql, tablenv);
                p.setVisible(true);
            }
        }
    }//GEN-LAST:event_tableqlMouseClicked

    private void tablenvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablenvMouseClicked
        int selectRow = tablenv.getSelectedRow();
        System.out.println(selectRow);
        TableModel model = tablenv.getModel();
        if (selectRow != -1) {
            int ask = JOptionPane.showConfirmDialog(this, "Bạn có muốn thay đổi chức vụ của: " + model.getValueAt(selectRow, 2));
            if (ask != -1) {
                ConfirmPass p = new ConfirmPass(username, (String) model.getValueAt(selectRow, 1), tableql, tablenv);
                p.setVisible(true);
            }
        }
    }//GEN-LAST:event_tablenvMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int ask = JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất ?");
        if (ask == 0) {
            form.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            DBAccess db = new DBAccess();
            displayPanel.setSelectedIndex(0);
            btnluu.setEnabled(false);
            btnboqua.setEnabled(false);
            bindSP();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    //Button thêm
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        action = 1;
        btnluu.setEnabled(true);
        btnboqua.setEnabled(true);
    }//GEN-LAST:event_jButton5ActionPerformed
    //Button xóa
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        action = 3;
        btnluu.setEnabled(true);
        btnboqua.setEnabled(true);
    }//GEN-LAST:event_jButton3ActionPerformed
    //Button sửa
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        action = 2;
        btnluu.setEnabled(true);
        btnboqua.setEnabled(true);
    }//GEN-LAST:event_jButton4ActionPerformed
    //Button thêm
    private void btnluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluuActionPerformed
        try {
            DBAccess db = new DBAccess();
            int idx = tablebanhang.getSelectedColumn();
            if (txtgiaban.getText().equals("") || txtmamh.getText().equals("") || txtmathang.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin sản phẩm");
                System.out.println(action);
                return;
            }
            String tenloai = (String) cbloaihang.getSelectedItem();
            String takeMALOAI = "Select MALOAI from LOAI_MAT_HANG where TENLOAI = N'" + tenloai + "' ";
            ResultSet checkQuery = db.ExQuery(takeMALOAI);
            String MALOAI = "";
            if (checkQuery.next()) {
                MALOAI = checkQuery.getString("MALOAI");
            }
            if (action == 1) {
                String checkMaMH = "Select * from MAT_HANG where MAMH = '" + txtmamh.getText() + "'";
                checkQuery = db.ExQuery(checkMaMH);
                if (checkQuery.next()) {
                    JOptionPane.showMessageDialog(null, "Mã mặt hàng không được trùng nhau");
                } else {
                    int dis = 0;
                    if (checkDis.isSelected()) {
                        dis = 1;
                    }
                    String insrt = "insert into MAT_HANG values ('" + txtmamh.getText() + "', N'" + txtmathang.getText() + "','" + Long.parseLong(txtgiaban.getText()) + "',N'" + cbdvt.getSelectedItem() + "', '" + MALOAI + "', N'" + txtmota.getText() + "','" + dis + "')";
                    int check = db.UpdateTable(insrt);
                    if (check == 1) {
                        JOptionPane.showMessageDialog(null, "Thêm sản phầm mới thành công");
                        bindSP();
                        setNULL();
                    } else {
                        JOptionPane.showMessageDialog(null, "Thất bại khi thêm sản phầm mới");
                    }
                }
            } else if (action == 2) {
                int dis = 0;
                if (checkDis.isSelected()) {
                    dis = 1;
                }
                TableModel df = tablebanhang.getModel();
                String update = "update MAT_HANG set TENMH= N'" + txtmathang.getText() + "', GIABAN='" + Long.parseLong(txtgiaban.getText()) + "',DVT=N'" + cbdvt.getSelectedItem() + "', MALOAI='" + MALOAI + "', MOTA=N'" + txtmota.getText() + "',VOHIEUHOA='" + dis + "' where MAMH='" + df.getValueAt(idxRow, 2) + "'";
                int ok = db.UpdateTable(update);
                if (ok == 1) {
                    JOptionPane.showMessageDialog(null, "Cập nhật sản phẩm thành công");
                    bindSP();
                    setNULL();
                } else {
                    JOptionPane.showMessageDialog(null, "Thất bại khi cập nhật");
                }
            } else if (action == 3) {
                TableModel tb = tablebanhang.getModel();
                int ask = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa " + tb.getValueAt(idxRow, 3));
                if (ask != -1) {
                    String q = "Delete FROM MAT_HANG where MAMH = '" + txtmamh.getText() + "'";
                    int res = db.UpdateTable(q);
                    if (res == 1) {
                        JOptionPane.showMessageDialog(null, "Xóa sản phẩm thành công");
                        bindSP();
                        setNULL();
                    }else JOptionPane.showMessageDialog(null, "Xóa sản phẩm thất bại");
                }
            }
            action = 0;
            btnluu.setEnabled(false);
            btnboqua.setEnabled(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnluuActionPerformed
    //Button bỏ qua
    private void btnboquaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnboquaActionPerformed
        // TODO add your handling code here:
        action = 0;
        setNULL();
    }//GEN-LAST:event_btnboquaActionPerformed
    public void setNULL() {
        txtmamh.setText("");
        txtmathang.setText("");
        cbloaihang.setSelectedIndex(0);
        cbdvt.setSelectedIndex(0);
        txtgiaban.setText("");
        btnluu.setEnabled(false);
        btnboqua.setEnabled(false);
    }

    //Vô hiệu hóa sản phẩm và cập nhật table
    int idxRow;
    private void tablebanhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablebanhangMouseClicked
        try {
            // TODO add your handling code here:
            DBAccess db = new DBAccess();
            int idxColumn = tablebanhang.getSelectedColumn();
            idxRow = tablebanhang.getSelectedRow();
            TableModel tb = tablebanhang.getModel();
            if (idxColumn == 0) {
                int ask = JOptionPane.showConfirmDialog(null, "Bạn có muốn vô hóa sản phẩm " + tb.getValueAt(idxRow, 2));
                if (ask != -1) {
                    String q = "update MAT_HANG set VOHIEUHOA = 1 where MAMH = '" + tb.getValueAt(idxRow, 2) + "' ";
                    int res = db.UpdateTable(q);
                    if (res == 1) {
                        JOptionPane.showMessageDialog(null, "Đã vô hiệu hóa thành công");
                        bindSP();
                    } else {
                        JOptionPane.showMessageDialog(null, "Có lỗi xảy ra khi vô hiệu hóa");
                    }
                }
            } else {
                cbloaihang.setSelectedItem(tb.getValueAt(idxRow, 1));
                txtmathang.setText((String) tb.getValueAt(idxRow, 3));
                txtmamh.setText((String) tb.getValueAt(idxRow, 2));
                txtmota.setText((String) tb.getValueAt(idxRow, 6));
                txtgiaban.setText((String) tb.getValueAt(idxRow, 4));
                cbdvt.setSelectedItem(tb.getValueAt(idxRow, 5));
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_tablebanhangMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        AddLoaiHangForm add = new AddLoaiHangForm(cbloaihang);
        add.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    public void bindTableQL() throws ClassNotFoundException, SQLException {
        DBAccess db = new DBAccess();
        String q = "select TENDANGNHAP,TENHANVIEN, SDT, GIOITINH, NGAYSINH from NHAN_VIEN where LAQUANLY = 1";
        ResultSet res = db.ExQuery(q);
        DefaultTableModel model = (DefaultTableModel) tableql.getModel();
        model.setRowCount(0);
        while (res.next()) {
            String temp = "";
            String username = res.getString(1);
            String name = res.getString(2);
            String SDT = res.getString(3);
            String GIOITINH = res.getString(4);
            String NGAYSINH = res.getString(5);
            String[] row = {temp, username, name, SDT, GIOITINH, NGAYSINH};
            model.addRow(row);
        }
    }

    public void bindTableNV() throws ClassNotFoundException, SQLException {
        DBAccess db = new DBAccess();
        String q = "select TENDANGNHAP,TENHANVIEN, SDT, GIOITINH, NGAYSINH from NHAN_VIEN where LAQUANLY = 0";
        ResultSet res = db.ExQuery(q);
        DefaultTableModel model = (DefaultTableModel) tablenv.getModel();
        model.setRowCount(0);
        while (res.next()) {
            String temp = "";
            String username = res.getString(1);
            String name = res.getString(2);
            String SDT = res.getString(3);
            String GIOITINH = res.getString(4);
            String NGAYSINH = res.getString(5);
            String[] row = {temp, username, name, SDT, GIOITINH, NGAYSINH};
            model.addRow(row);
        }
        //tablenv.getColumnModel().getColumn(0).setCellRenderer(new NVRender());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainForm(form, username).setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnboqua;
    private javax.swing.JButton btnluu;
    private javax.swing.JButton btnphanquyen;
    private javax.swing.JComboBox<String> cbdvt;
    private javax.swing.JComboBox<String> cbloaihang;
    private javax.swing.JCheckBox checkDis;
    private javax.swing.JTabbedPane displayPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tablebanhang;
    private javax.swing.JTable tablenv;
    private javax.swing.JTable tableql;
    private javax.swing.JTextField txtgiaban;
    private javax.swing.JTextField txtmamh;
    private javax.swing.JTextField txtmathang;
    private javax.swing.JTextArea txtmota;
    private javax.swing.JLabel usernameds;
    // End of variables declaration//GEN-END:variables
}
